### ISSUE TITLE
Deprecated Inventory object?

### ISSUE THREAD

**Issue by developer-sumit-thakur** [googlesamples/android-play-billing#100]
1. In the previous library as we were getting Inventory object, how can we get it in library version 1.0?
2. How can we get developer payload, which we are getting in Purchase object?
3. How to show a list of subscription options while changing subscription? 
I tried : initiatePurchaseFlow(skuID, new ArrayList<String>(oldSkus), BillingClient.SkuType.SUBS); 
this always show Error : 7 

For reference :
**public void onQueryInventoryFinished(IabResult result, Inventory inventory) {
            Log.d(TAG, "Query inventory finished.");
}**

& for developer payload : 
https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/app/src/main/java/com/example/android/trivialdrivesample/util/Purchase.java

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://issuetracker.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.
