### ISSUE TITLE
onPurchasesUpdated bug very serious 

### ISSUE THREAD

**Issue by cgw0827** [googlesamples/android-play-billing#127]
@Override
    public void onPurchasesUpdated(int resultCode, List<Purchase> purchases) {

        Log.i(TAG, "onPurchasesUpdated resultCode "+resultCode);
        if(purchases == null){
            Log.i(TAG,"onPurchasesUpdated purchases is null ");
        }
        if (resultCode == BillingResponse.OK && purchases != null) {
            for (Purchase purchase : purchases) {
                handlePurchase(purchase);
            }

        } else if (resultCode == BillingResponse.USER_CANCELED) {
            returnPayResult(EventName.PURCHASE_CANCELLED,getMessage(resultCode,"Purchase Cancelled",null));
        } else if(resultCode == BillingResponse.ITEM_ALREADY_OWNED){

            queryInventory("");
            returnPayResult(EventName.PURCHASE_ITEM_OWNED,getMessage(resultCode,"If you still can't buy the item, please clear the data of Google Store and restart the game.",null));
        }else{
            returnPayResult(EventName.PURCHASE_FAILED,getMessage(resultCode,"Purchase Failed",null));
        }
    }

I disconnect immediately when I clicked the purchase button from Google SDK. Then I reconnect and wait for the success message from SDK. At this moment, the function onPurchaseUpdated was called. resultCode = BillingResponse.OK, but purchases = null. And no matter use the queryPurchaseHistoryAsync or the queryPurchases, both have no purchase info for this item.
When I try to buy this item,  it tells me I already owned it. Unless I clear the Google store cache data, I can receive the data from queryPurchases function. But the function queryPurchaseHistoryAsync still can’t get this billing info.

**Comment by dorinionescu** [comment]
Yes this is a big Google Pay conception error (they should add another API function here for online pucrchase check)
1. queryPurchases fail on it's empty cache response is the reason why we call Buy in order to Buy or Refresh purchase info.
2. Then Buy answer = ITEM_ALREADY_OWNED is a confirmation of bad Cache as this is an online check on server. It confirms you that the cache is bad and queryPurchase answers are bad 
3. Purchased list is unfortunately empty (on onPurchasesUpdated listener) so we can workaround with SKU-id of the BUY button (but this is very dangereux as we may have a lot of items on Async try to Buy)
Here we should be let to transmit "place info" of our own that we should received back.
4. queryPurchaseHistoryAsync is a joke anyway (no buy info, some shoppings can be canceled or expired) I understand that this is just an info for the user that we acknowledge his money operations 

So where is another API function from Google to get online info ? Is Iabhelper better or is just another construction on a bad API project ?

**Comment by stephanedupont** [comment]
I have more and more users reporting this problem to me. Please fix it Google!

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.

**Comment by terrelewis** [comment]
Any updates on this issue. I'm trying to upgrade a subscription from a monthly plan to yearly plan and everything works fine wherein I get a "Subscribed" successful message. However, in `onPurchasesUpdated`, I get a success response but a null purchase list. Why is this happening?

**Comment by xyear** [comment]
> Any updates on this issue? I'm trying to upgrade a subscription from a monthly plan to yearly plan and everything works fine wherein I get a "Subscribed" successful message. However, in `onPurchasesUpdated`, I get a success response but a null purchase list. Why is this happening?


I encountered the same problem，have any solution？

**Comment by raphael-anydo** [comment]
I have observed the exact same issue: upon purchase of a Subscription, the `onPurchasesUpdated` callback gets called with `BillingClient.BillingResponseCode.OK` but the purchases are empty.

**Comment by agGitHub** [comment]
Any update about this crazy bug ? How to solve it with Google Play Billing v3 ? Does v4 solve it ? Thanks
