### ISSUE TITLE
PriceAmountMicros and PriceCurrencyCode Not Matched

### ISSUE THREAD

**Issue by Colibrow** [googlesamples/android-play-billing#137]
Hi, I use the priceAmountMicros and priceCurrencyCode to record the money used but I found sometimes I paid in 0.55 USD for example, but GP returns the 96 USD because I located at PT(Portuguese) , afaik 94PTE  = 0.55USD ,but the 96 USD is so misleading, how can i avoid this

**Comment by dearmash** [comment]
The price per country is set in the play developer console and doesn't actively track the current exchange rates.  It'd be up to you to go in to the console in order to maintain these prices.

I'm not sure if that's your question, or if there's actually a mismatch, where it's returning the price of one, but currency of another.

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
