### ISSUE TITLE
Using promo code results in 'Item Already Owned'

### ISSUE THREAD

**Issue by atsikno** [googlesamples/android-play-billing#15]
Issue #7 discusses the problem of promo codes and having no developerPayload. 

However, even without validation of developerPayload there is an issue in that if you initiate payment from the app but pay with a promo code the workflow results in an 'item already owned'  failure in  onIabPurchaseFinished. In fact the 'payment' goes through, but the user (and the app itself) don't know that!

I think this is happening 100% of the time, but it possibly depends on whether or not the app is notified of the purchase before the standard purchase flow completes?

**Comment by StephaneDupont** [comment]
I confirm this.

I've been encountering the same think with a non-consumable in-app product.

When redeeming a promo code from inside the app, there's first a Google popup that says something like "Item added", then the user click on "OK", then there's another Google popup that says "Item already owned".

After that, here's the log I got when returning to the app:

Purchase finished: IabResult: User canceled. (response: -1005:User cancelled), purchase: null

**Comment by rpattabi** [comment]
I am facing the exact problem. I am surprised not many seem to be facing this. Probably not many tried promo codes which is somewhat recent for play store? I wonder.

**Comment by SanjibBhowal** [comment]
I am also facing the same problem. If I enter promo code from the dropdown and the click redeem code then promo codes are working but if I click continue button and then redeem code then i am getting item already owned and response:- -1005: User cancelled purchase.

**Comment by rpattabi** [comment]
This issue is because of the following:

1. The purchase using promo code actually happened and google play has the transaction as successful.
1. The app is validating the developer payload.
1. Interestingly (and frustratingly), google play does not provide developer payload. So the purchase from app point of view is invalid.
1. So if another promo code is tried out when the product is already purchased (as per google play records), we get "Item Already Owned" error from google play since an item cannot be purchased more than once.

Not having developer payload is the key problem with promo codes as of now.

Only solution is to allow the user to consume purchase somehow, so that they will be able to make a purchase again. 

Do not use promo codes if you are validating developer payload. It is unclear if Google is even working on this long pending issue.

**Comment by StephaneDupont** [comment]
@rpattabi It happens even without validating developer payload, so I'm not sure this is the problem here.

**Comment by rpattabi** [comment]
@StephaneDupont Promo code purchase(s) made when the app was validating (and failing), should be consumed, prior to purchasing again. Till then purchase of that item will be showing this error whether you updated your app not to validate or not.

**Comment by aritraroy** [comment]
I am facing the exact same issue. Any way to fix this?

**Comment by Lightlink-App-developer** [comment]
I am also facing the same....any update?

**Comment by netomarin** [comment]
Hi all

As mentioned on issue #7 the developerPayload is not recommended for security validations, because is not supported across all Google Play features.
Our recommendation is to perform server-side validation.

Best regards,
Neto

**Comment by atsikno** [comment]
This shouldn't have been closed, DeveloperPayload isn't relevant. 
From the original post:
"even without validation of developerPayload there is an issue in that if you initiate payment from the app but pay with a promo code the workflow results in an 'item already owned' failure..."

**Comment by rpattabi** [comment]
@atsikno Please review the possible steps through with you ran into the issue. Are you ensuring that the in-app product is consumed prior to trying with the promo code again?

**Comment by PrithiviRajG** [comment]
I am also facing the same issue

**Comment by EduardoNogueira** [comment]
I am facing this issue, any update?
