### ISSUE TITLE
Owned subscription returns responseCode 6 not 7

### ISSUE THREAD

**Issue by Lingviston** [googlesamples/android-play-billing#16]
When I have subscription and try to buy same subscription, dialog from Google Play show:

You're already subscribed to...
But the responseCode passed in Intent within onActivityResult method is 6.
When I look to Constants:
BILLING_RESPONSE_RESULT_ERROR = 6; //Fatal error during the API action

But it should return: BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED = 7; //Failure to purchase since item is already owned

**Comment by netomarin** [comment]
@Lingviston this was fixed in our side.
Thanks for reporting.

And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
