### ISSUE TITLE
Google Play In-app Billing API version is less than 9

### ISSUE THREAD

**Issue by yoursungjin** [googlesamples/android-play-billing#206]
PlayStoreBillingClient#acknowledgePurchase returns
'Google Play In-app Billing API version is less than 9'.

Could you help us with this issue?

```
    private fun acknowledgeNonConsumablePurchasesAsync(nonConsumables: List<Purchase>) {
        nonConsumables.forEach { purchase ->
            val params = AcknowledgePurchaseParams.newBuilder().setPurchaseToken(purchase
                    .purchaseToken).build()
            playStoreBillingClient.acknowledgePurchase(params) { billingResult ->
                when (billingResult.responseCode) {
                    BillingClient.BillingResponseCode.OK -> {
                        disburseNonConsumableEntitlement(purchase)
                    }
                    else -> Log.d(LOG_TAG, "acknowledgeNonConsumablePurchasesAsync response is not OK ${billingResult.debugMessage}")
                }
            }

        }
    }
```
Pixel 2 
Android 8.1.0 API 27
com.android.billingclient:billing:2.0.1

**Comment by c6collin** [comment]
This happens when the purchase is made on a device which does not have an updated Playstore. When the user's device does not support acknowledgement you are not required to acknowledge the purchase since it's not possible on that device. To detect this you can check the isAcknowledged() method on the purchase which will return true in this case.

**Comment by yoursungjin** [comment]
@c6collin 
Thank you for the answer, I really appreciate that.
If there are any other things similar to this, please let me know.
