### ISSUE TITLE
I don't know what happend on users' phone

### ISSUE THREAD

**Issue by HaustWang** [googlesamples/android-play-billing#209]
I added this billing code to my project, and I collect users' payment, I found that users click buy button but our application can't get any result. How can I know what user happened?

**Comment by leventepal** [comment]
I am having the same issue. I have analytics in my app and I can see that people are pressing the button but nothing happens. What have I done is I tried to purchase using a different gmail account (which is not a tester) and I could reproduce the issue. I'm using 2.0.1 version.

Beside analytics I'm having a custom built logging system and from the logs I can see that the Google Play Service doesn't offer the in-app products.

What is surprising that 2 days ago everything was working fine, but yesterday and today it looks like the service is down. I think Google Play Services/Billing service is faulty here because suddenly the in-app purchases stopped working.

Note: I didn't updated the app, I didn't made any modification in the app. Everything was working fine until 2 days ago.

**Comment by HaustWang** [comment]
@leventepal Hello. I used the aidl interface before, these two days, I want to update to use 2.0.1 version, but when I click the buy button, the dialog shows "Something went wrong on our end. Please try again.". Did you know how to do?
