### ISSUE TITLE
Use this library or roll my own?

### ISSUE THREAD

**Issue by trans** [googlesamples/android-play-billing#30]
Is this project maintained enough to be used as a library or is it strictly an example?

**Comment by rpattabi** [comment]
In my understanding, this project is maintained enough as far as an example is concerned. However, this is strickly to be used as example. The comments point out in several places that shortcuts were taken. So you shall definitely _adapt_ what you pull from it.

I hope someone from google could provide the official view.

**Comment by netomarin** [comment]
Hi @trans 
This is our official sample for implementing In-App Billing API V3, but is strictly a sample and you should not use sample code in production app, for you own security.

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
