### ISSUE TITLE
Your app is using an incorrect implementation of in-app billing

### ISSUE THREAD

**Issue by sssemil** [googlesamples/android-play-billing#31]
> If you are manually invoking the in-app billing service, make sure you are calling Intent.setPackage(“com.android.vending”) on any intents to "com.android.vending.billing.InAppBillingService.BIND".

That's what an email from Google Play says. Cheers.

**Comment by umair6** [comment]
Any update on this issue? I am facing this issue too.

**Comment by sssemil** [comment]
Nope. I've only found this question on stackoverflow - http://stackoverflow.com/questions/38642622/google-play-warning-incorrect-implementation-of-google-play-inapp-billing

**Comment by netomarin** [comment]
@sssemil it happens because you are using the wrong code to run in-app billing requests.
Please check our docs and sample.

And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
