### ISSUE TITLE
When purchasing in several devices with the same account, the refresh inventory does not return the correct result

### ISSUE THREAD

**Issue by neteinstein** [googlesamples/android-play-billing#38]
I'm using 2 devices with the same Google account, let's call them Nexus 1 and Nexus 2.
1. Open the app on Nexus 1
2. I buy a product on Nexus 1.
3. Success
4. Open the app on Nexus 2 (less than 1 minute after)
5. Buy product 
6. Failed (popup from In App Billing says the the app is already bought)
7. Refresh inventory -> returns that item **without it being marked as bought** 

I haven't been able to detect that the failed purchase error has the information that the item is already bought (that way I could circunvent this error).

I believe this is some kind of cache on the Play Store that is only refresh a bit after, since eventually it returns the inventory correctly.

I have some logs to prove it, but I don't think they add much value, still if need I can attach them.

**Comment by netomarin** [comment]
Hi @neteinstein 

All products on In-App Billing API are managed, so you need to consume them before it available again for purchase. And your user's inventory is your responsibility to control.
See [Consuming purchase](https://developer.android.com/google/play/billing/billing_integrate.html#Consume) for more details.

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
