### ISSUE TITLE
Response - 1005 : User Cancelled

### ISSUE THREAD

**Issue by GauravCreed** [googlesamples/android-play-billing#44]
Hi @ryanseys 

I got **IabResults : User Canceled. (Response : - 1005 : User Cancelled)** is there any solution for that??
When i click on any of the Image like , **Buy Gas, Upgrade My Car , Get Infinite Gas**. is it any mistake done by me ?

Thanks.

**Comment by netomarin** [comment]
Hi @ryanseys 

To answer your question we need more details about your code and implementation.
Check you LogCat for further details.

And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.

**Comment by ryanseys** [comment]
not sure what I had anything to do with this but 👍

**Comment by gorgon** [comment]
Usually, **User Cancelled** means that buyer didn't decide to continue into our Purchase flow, by clicking on back button or outside of our Purchase dialog.
So it could happen if you clicked on the button twice (first click - launched the dialog, second - canceled the flow). Otherwise, please, try to clone the github repo from the scratch. You should be able to see Purchase dialog once you carefully follow these instructions: https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/README.md
