### ISSUE TITLE
Inadequate instructions in the README

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-play-billing#47]
Hello,
your README states to **test the code by running the APK signed with PRODUCTION certificate**.  However, this is not adequate.  The developer needs to actually go to their Play Developer Console, add email addresses for Closed Alpha Testing, then navigate to the Opt-In URL in the phone's browser:
![optin](https://cloud.githubusercontent.com/assets/201209/21017016/db88fd2c-bd35-11e6-837d-3e355962b498.png)

Then, they need to download the APK from the browser.  ONLY THEN can they test this APK.

According to a Google Play Developer expert support chat I just had:
> Closed Alpha testing is a way to limit availability of the Alpha release to a list of specific users/testers. Only these testers will be able to access the app via the Opt-In link. 
Open Alpha is a way for anyone with the link to access the app.

You really need to update your README to tell developers to take this crucial step.  I spent almost a day figuring this nuance out.

Igor

**Comment by IgorGanapolsky** [comment]
And according to these instructions - https://developer.android.com/google/play/billing/billing_testing.html:

![screen shot 2016-12-08 at 11 26 20 am](https://cloud.githubusercontent.com/assets/201209/21017980/2edc6768-bd39-11e6-8e37-b45b114715cc.png)

**Comment by netomarin** [comment]
Hi @IgorGanapolsky 

Actually, the mention about the production key is because you need to upload at least one APK with the correct permission and signed with your production key to be able to do static tests, to do test purchases or you can go into Developer Console, go to Settings > Account details, then in the License Testing section, add the addresses to Gmail accounts with testing access field.

And about alpha/beta, we already changed the interface and the doc is up to date.

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.

**Comment by IgorGanapolsky** [comment]
Thank you for the explanation.
