### ISSUE TITLE
This version of the application is not configured for billing through Google Play

### ISSUE THREAD

**Issue by upendrashah47** [googlesamples/android-play-billing#51]
I am developing a demo of in-app billing in which i used two manged product and two subscription. Actually Its working till version code 6 and publish 6 builds that all are working but after version code 6 I updated to in-app billing version 3 its not working. Now I got error **This version of the application is not configured for billing through Google Play. Check the help center for more information** I can not find any solution. is there any setting changes in google developer account from where i published my application???

Please Help me to solve out..

Thanks ..

**Comment by avipars** [comment]
Yes, you need to have a version of the app in the play store. and you probably pushed the apk from your computer causing this response. So use another google account and download a version from the play store.

**Comment by netomarin** [comment]
Hi @upendrashah47 

Recently we implemented a change on our systems, and since you have uploaded at least one APK to your console, you can test your in-app requests with your app with any version code / number.

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.

**Comment by RobertTadevosyan** [comment]
https://www.revenuecat.com/docs/google-play-store
