### ISSUE TITLE
getPurchaseHistory() doesn't work

### ISSUE THREAD

**Issue by nbarishok** [googlesamples/android-play-billing#53]
I have troubles getting **getPurchaseHistory()** to work. The code is as simple as:

`Bundle purchaseHistoryBundle = mService.getPurchaseHistory(7, BuildConfig.APPLICATION_ID, "subs", null, new Bundle());`

Response I get is **BILLING_RESPONSE_RESULT_ERROR = 6**

What s wrong with the code?

**Comment by netomarin** [comment]
Hi @nbarishok 

You can see the list with all codes [here](https://developer.android.com/google/play/billing/billing_reference.html#billing-codes).

About your code, If BuildConfig.APPLICATION_ID is not your application package (String), you probably should receive this error.

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
