### ISSUE TITLE
I dont get to test 

### ISSUE THREAD

**Issue by rviannaoliveira** [googlesamples/android-play-billing#55]
I have implemented purchase in my owner app, so i read the documentation of google, but when i was trying test using:
*android.test.purchased
*android.test.canceled
*android.test.item_unavailable
i dont get to test, i was analyzing the code, and i identify that the class Securiy inside the method verifyPurchase, it was blocking for test. I proposed  the modification this method to use to test.( I already did)

If I am wrong, can you give feedback?,
i hope have helped  
Tks.

**Comment by netomarin** [comment]
Hi @rviannaoliveira 

This that you mention is test with [static responses](https://developer.android.com/google/play/billing/billing_testing.html#billing-testing-static), and when testing with static responses, the orders are not signed, so you can't use the class Security, because this class is used to validate signatures.

So, when testing with static response you can't validate the purchase signature.
We are going to update our docs soon, to explain this better.

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
