### ISSUE TITLE
Inserting developerPayload to launchBillingFlow()

### ISSUE THREAD

**Issue by mitrakov** [googlesamples/android-play-billing#67]
Is it possible to insert `developerPayload` to `BillingClient`'s `launchBillingFlow()` method? As far as I understand this method puts `NULL` as an argument for `getBuyIntent()`

**Comment by tucson-tom** [comment]
I just discovered that `developerPayload` doesn't always work.  In several instances, for example when using a promo code, a later call to getPurchases() will not include the information that was sent.  This limitation makes `developerPayload` useless.  Google's official stance is that it should NOT be used for security purposes even though a bunch of documentation and the official Trivial Drive example say otherwise.  Hope this saves you some time.

**Comment by mitrakov** [comment]
Oh, it's a pity...
Thanks for the answer!
