### ISSUE TITLE
Fix Android Studio support for IAB

### ISSUE THREAD

**Issue by tucson-tom** [googlesamples/android-play-billing#69]
I realize this probably isn't the right place to make this request but I don't know where this request should be directed to.

Android Studio support for IAB is basically non-existent.  Users who want to test real-world IAB apps have to leave Android Studio after generating a Signed APK with the same version as that in Google Play and use the command-line to uninstall, install, and enable debugging mode.  Only then can Android Studio attach to the waiting debugger.  It's incredibly inefficient.

In addition, a complete application has to be registered in Google Play including a published dummy APK to Alpha or Beta and a merchant account set up **before** IAB can actually be implemented in the application in Android Studio.

The IAB development cycle is, hands-down, the most broken feature in Android Studio.

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://b.corp.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.
