### ISSUE TITLE
Add IAB getFullPurchaseHistory() API

### ISSUE THREAD

**Issue by tucson-tom** [googlesamples/android-play-billing#71]
I realize this probably isn't the right place to make this request but I don't know where this request should be directed to.

The getPurchaseHistory() API returns only the most recently purchased item.  This makes it impossible to track how many times an item has been purchased and consumed as well as being unable to show the user an actual history of their in-app purchases from within the app itself.  The current getPurchaseHistory() can be useful but there should be a way to retrieve ALL purchases.

This should be flagged as critical priority as it affects certain financial reconciliation processes, makes registering some products in Google Play a massive pain in the neck, and requires writing special and rather fragile code to handle the aforementioned products.

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://b.corp.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.
