### ISSUE TITLE
Raise limit for Google Play IAB descriptions to something sane

### ISSUE THREAD

**Issue by tucson-tom** [googlesamples/android-play-billing#72]
I realize this probably isn't the right place to make this request but I don't know where this request should be directed to.

The limit for a title is 55 characters.  "Okay, fine.  Whatever.  I'll cram the rest in the description."

The limit for a description is 80 characters.  "Really?!  What's the point?"

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://b.corp.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.
