### ISSUE TITLE
How do i get User Purchases when app Launches?

### ISSUE THREAD

**Issue by Edge-Developer** [googlesamples/android-play-billing#88]
as Described here [StackOverflow]( https://stackoverflow.com/questions/46470190/how-do-i-query-for-user-purchases-when-app-starts-play-billing-1-0)

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://b.corp.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.
