### ISSUE TITLE
Unable to Compile project in Android Studio 2.3.3 and Android studio 3 Beta 7!

### ISSUE THREAD

**Issue by Neven123** [googlesamples/android-play-billing#94]
Hello 

Project want compile in AS 2.3.3 with error "This Gradle plugin requires Studio 3.0 minimum"

In And. Std. 3.0 compile is not working as well; First Issue was with build tools error, for which I had to change version numbers in Gradle   
   TARGET_SDK_VERSION = 26
    TOOLS_VERSION = "26.0.2"
    SUPPORT_VERSION = "26.0.2"

After that Project would build, but before project start on emulator error would occur:
Error:Execution failed for task ':mobile:validateSigningDebug'.
> Keystore file C:\...\GitHub\android-play-billing\TrivialDrive_v2\mobile\myStoreFileLocation not found for signing config 'release'.

Any help would be appreciated ?

**Comment by cartland** [comment]
It sounds like you have raised two separate issues. The first is Gradle plugin, and you were able to resolve that issue with Android Studio 3.0. The version numbers for each dependency might need to be updated depending on which version of Android Studio you are using.

The second issue is related to the signing config. You should update `keystore.properties` with the signing config information. `myStoreFileLocation` should be replaced with your `.jks` filename, and the keystore should be placed in the `mobile`, `tv`, `wear`, and `base-feature` module directories so that each module can be signed with the correct keys.
[TrivialDrive_v2/keystore.properties](https://github.com/googlesamples/android-play-billing/blob/2ef1ee0551d2150bca7500e0228a624f3abf5832/TrivialDrive_v2/keystore.properties)

The signing configuration is based on [Remove signing information from your build files](https://developer.android.com/studio/publish/app-signing.html#secure-shared-keystore).

**Comment by Neven123** [comment]
Thanks for pointing me in the right direction. I have solved that issue by adding following into Gradle for mobile, shared-module, base-feature.

android {
    signingConfigs {
        release
                {
                    keyAlias 'KeyBilling2'
                    keyPassword 'android'
                    storeFile file('C:/Projects/KeyStore/BillingKey2.jks')
                    storePassword 'android'
        }

        debug{
            keyAlias 'KeyBilling2'
            keyPassword 'android'
            storeFile file('C:/Projects/KeyStore/BillingKey2.jks')
            storePassword 'android'
        }
    }
