### ISSUE TITLE
Request: for BillingManager, have the BASE_64_ENCODED_PUBLIC_KEY be a parameter in its initialization

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-play-billing#96]
Or via its CTOR.

The reason is that we could use this class alone into our app, with minimal modification.

**Comment by gorgon** [comment]
Please don't try to use everything related to security without modifications!
You should implement the security layer by yourself - Play Billing library just provides a mechanism for easy integration with Play Billing and doesn't have any security level. So we do recommend for every developer to create your own security mechanism, make it unique and obfuscate it as much as possible. And also keep in mind, that such approach will not be secure on 100%, since Java code could be decompiled. So please consider having a security layer at your backend and utilize Google's [backend API](https://developers.google.com/android-publisher/api-ref/purchases/products/get) as well.

**Comment by AndroidDeveloperLB** [comment]
Exactly, which is why I think it shouldn't be the way you did it.
It shouldn't be in a constant field.
It should be in an abstract method, Something like "generateKey()", so that the class that extend it must provide a better way to provide it, other than a simple constant.

Alternatively, an even better solution: BillingManager should be abstract, with this method returning null, and if it's really null, throw an exception telling it should generate the real key instead.

The current way the code is written, doesn't allow to extend the BillingManager properly. We have to modify the class ourselves. 
That's not a nice API to use this way. It should be more generic and easy to use.
Just as the sample name "trivial" ...

**Comment by gorgon** [comment]
Please, don't use TrivialDrive_v2 sample app inside your code! It's just to demonstrate the API of the new library.
Copy/pasting is also not the best approach in Software Engineering. That's why [Play Billing library](https://developer.android.com/google/play/billing/billing_library.html) was created.
Just implement your own application in the way you prefer.

**Comment by AndroidDeveloperLB** [comment]
Previous sample was used fine in code, where it was possible and made sense. Only parts that needed to change is the key-generation, and what parts to use for purchasing and what to do with them.
I just want to use the new library because I noticed that the sample has some exceptions that aren't handled correctly.

Copy-Paste is something all of developers do and should. A good developer should know what parts to stitch and how to stitch them. 
The moment you use a repo using gradle, you copy-paste the code of it into your project. It doesn't matter if it's open sourced or not. 
Once I use this line:
compile 'com.android.billingclient:billing:1.0'
I copy a lot of code that it wasn't me who wrote it.

StackOverflow is a great example of a website that developers help each other. If it was told not to copy-paste, there would be too general answers there that are hard to understand or use, or even talk about, including reviewing them and telling what's wrong. 
Open source is great.

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

Please reopen if you still think this is an issue with the sample.

**Comment by AndroidDeveloperLB** [comment]
@pfmaggi It is about the sample. Why close it?
